app/scf_app/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'issues#home'
  post '/issues/stats_by_neighborhood' => 'issues#stats_by_neighborhood'
  post '/issues/stats_by_request_type' => 'issues#stats_by_request_type'
  post '/issues/stats_by_request_type_and_neighborhood' => 'issues#stats_by_request_type_and_neighborhood'

  get '/clusters' => 'clusters#home'
  get '/clusters/index/:rtid' => 'clusters#index'
  get '/clusters/:id_' => 'clusters#show', as: 'cluster'

  get '/issues/stats_by_neighborhood' => 'issues#home'
  get '/issues/stats_by_request_type' => 'issues#home'
  get '/issues/stats_by_request_type_and_neighborhood' => 'issues#home'

  get'/clusters/show' => 'clusters#home'

end

app/scf_app/app/models/cluster.rb
class Cluster < ActiveRecord::Base
  has_many :issues ,{:primary_key => 'id_'}
  self.primary_key = 'id_'
end

app/scf_app/app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :cluster, {:foreign_key=>'cluster_id'}
end

app/scf_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/scf_app/app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  layout :resolve_layout
  def home
    @request_types=Cluster.select("rtt","rtid").distinct
  end
  def index
    request_type=params[:rtid]
    @clusters=Cluster.where(:rtid=>request_type).order(score: :desc)
    @request_type=@clusters[0][:rtt]
  end
  def show
    @cluster=Cluster.find(params[:id_])
    @issues=Cluster.find(params[:id_]).issues
  end
  def resolve_layout
    case action_name
    when "show"
      "clusters_show_layout"
    else
      "clusters_layout"
    end
  end
end

app/scf_app/app/controllers/issues_controller.rb
require "time"

class IssuesController < ApplicationController
  Request_types=[
    "Bins for Trash & Recycling",
    "Graffiti",
    "Hangers",
    "Health Complaints",
    "Illegal Dumping",
    "Other",
    "Other - city responsibility",
    "Parking Violation/Abandoned Auto",
    "Parks Request",
    "Policing Issue",
    "Potholes",
    "Private Property Issue",
    "Public Space, Streets and Drains",
    "Sidewalks and Curb damage",
    "Signs / Bus Shelters / Pavement Markings",
    "Street Lamp",
    "Street Sweeping",
    "Traffic/Road Safety",
    "Traffic Signal / Pedestrian Signal",
    "Trash & Recycling",
    "Tree Trimming"
  ]
  Neighborhoods=[
    "Annex",
    "Beaver Hills",
    "Dixwell",
    "Downtown",
    "Dwight",
    "East Rock",
    "East Shore",
    "Edgewood",
    "Fair Haven",
    "Fair Haven Heights",
    "Hill",
    "Long Wharf",
    "Newhallville",
    "Prospect Hill",
    "Quinnipiac",
    "West River",
    "West Rock",
    "Westville",
    "Wooster Square/Mill River"
  ]
  def home
  end

  def stats_by_neighborhood
    @stats=get_stats(:neighborhood,params[:days_back].to_i)
  end

  def stats_by_request_type
    @stats=get_stats(:rtt,params[:days_back].to_i)
  end

  def stats_by_request_type_and_neighborhood
    @request_type=params[:request_type]
    @stats=get_stats(:both,params[:days_back].to_i,request_type=params[:request_type])
  end

  ## construct parameters using get_stats
  ## and execute query using query_issues

  def query_issues(parameters)
    issues=Issue.where(parameters)
    total_time,count,acknowledged,closed=0,0,0,0
    issues.each do |issue|
      if issue["acknowledged_at"]!=nil
        acknowledged+=1
        if issue["closed_at"]!=nil
          total_time+=(issue["created_at"]).to_i-(issue["closed_at"]).to_i
          closed+=1
        end
      end
      count+=1
    end

    if count >0
      avg_fix_time=(total_time.to_f/(count*1000*60*60*24)).round
      n_issues=count
      acknowledge_rate=acknowledged.to_f/count.to_f
      fix_rate = closed.to_f/acknowledged
      stat= {
            :n_issues=>n_issues,
            :acknowledge_rate=>acknowledge_rate,
            :fix_rate=>fix_rate,
            :avg_fix_time=>avg_fix_time
            }
    end
    return stat
  end

  def get_stats(param,days_back=nil,request_type=nil)
    stats=[]
    if param == :neighborhood
      Neighborhoods.each do |val|
        parameters= {param=>val}
        if not days_back==0
          parameters[:created_at] = (Time.now.midnight - days_back.day)..Time.now.midnight
        end
        stat=query_issues(parameters)
        if stat
          stat[param]=val
          stats.push stat
        end
      end
    elsif param == :rtt
      Request_types.each do |val|
        parameters= {param=>val}
        if not days_back==0
          parameters[:created_at] = (Time.now.midnight - days_back.day)..Time.now.midnight
        end
        stat=query_issues(parameters)
        if stat
          stat[param]=val
          stats.push stat
        end
      end
    elsif param == :both
      Neighborhoods.each do |val|
        parameters= {:neighborhood=>val,:rtt=>request_type}
        if not days_back==0
          parameters[:created_at] = (Time.now.midnight - days_back.day)..Time.now.midnight
        end
        stat=query_issues(parameters)
        if stat
          stat[:neighborhood]=val
          stats.push stat
        end
      end
    end
    return stats
  end
end

app/scf_app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/scf_app/app/helpers/clusters_helper.rb
module ClustersHelper
end

app/scf_app/app/helpers/issues_helper.rb
module IssuesHelper
end

app/scf_app/app/views/clusters/home.html.erb
<h2>Please Make a Selection Below</h2>
<% @request_types.each do |request_type| %>
<%= link_to request_type[:rtt],'/clusters/index/'+request_type[:rtid] %>
<% end %>

app/scf_app/app/views/clusters/index.html.erb
<h1><%= @request_type %></h1>
<h2>All Clusters</h2>
<% @clusters.each do |cluster|%>
  <%= link_to "more",cluster_path(cluster),:target => "_blank"%>
  <%= cluster[:score] %>
  <% cluster.issues.select(:street_name).distinct().each do |street| %>
    <%=street[:street_name]  %>
  <% end %>
  </br>
<% end %>

app/scf_app/app/views/clusters/show.html.erb
<h1> <%=@cluster[:rtt] %></h1>
<h2>  cluster # <%=@cluster[:id_]%> </h2>
<div id="list">
  <table>
    <tr>
      <td>link</td>
      <td>created</td>
      <td>status</td>
      <td>street</td>
    </tr>
  <% @issues.each do |issue|%>
    <tr>
      <td><%= link_to "view issue","https://seeclickfix.com/issues/"+issue[:id_].to_s,:target=>"blank"%></td>
      <td><%= issue[:created_at]%></td>
      <td><%= issue[:status] %></td>
      <td><%= issue[:street_name]%></td>
    </tr>
    <% end %>
  </table>
</div>

<!-- create a map div -->
<div id='map' style="width:300px;height:300px"></div>

<!-- display map-->
<%= javascript_tag do %>
  var map;
  function initMap(category) {
    // Create a map object and specify the DOM element for display.
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 41.31, lng: -72.898197},
      scrollwheel: false,
      zoom: 8
    });

  //debugger;

  //create array of longitude, latitude coordinates
  var geo_data=[]
  var latlngbounds = new google.maps.LatLngBounds();
  <% @issues.each do |issue| %>
    var lat = <%=issue[:lat]%>
    var lng = <%=issue[:lng]%>
    geo_data.push(new google.maps.LatLng(lat,lng));
  <% end %>

  //use geo_data to create bounds and populate the map
  geo_data.forEach(function(loc){
          latlngbounds.extend(loc);
          var color = "blue";
          //if (meta_data[i]['status']==="Open"){color="red"}
          var Circle = new google.maps.Circle({
            strokeColor: color,
            strokeOpacity: 0.8,
            strokeWeight: .5,
            fillColor: color,
            fillOpacity: 0.35,
            map: map,
            center: loc,
            radius: 4
          });
  });
  map.setCenter(latlngbounds.getCenter());
  map.fitBounds(latlngbounds);
}
<% end %>

app/scf_app/app/views/issues/home.html.erb
<h3>Please make selection above.</h3>

app/scf_app/app/views/issues/stats_by_neighborhood.html.erb
<p>Results!</p>
<table>
  <tr>
    <td>neighborhood</td>
    <td>number of issues</td>
    <td>acknowledge rate</td>
    <td>fix rate</td>
    <td>average fix time (days)</td>
  </tr>
  <% @stats.each do |stats|%>
    <tr>
      <td><%= stats[:neighborhood] %></td>
      <td><%= stats[:n_issues] %></td>
      <td><%= stats[:acknowledge_rate] %></td>
      <td><%= stats[:fix_rate] %></td>
      <td><%= stats[:avg_fix_time] %></td>
    </tr>
  <% end %>

</table>

app/scf_app/app/views/issues/stats_by_request_type.html.erb
<p>Results!</p>
<table>
  <tr>
    <td>request_type</td>
    <td>number of issues</td>
    <td>acknowledge rate</td>
    <td>fix rate</td>
    <td>average fix time (days)</td>
  </tr>
  <% @stats.each do |stats|%>
    <tr>
      <td><%= stats[:rtt] %></td>
      <td><%= stats[:n_issues] %></td>
      <td><%= stats[:acknowledge_rate] %></td>
      <td><%= stats[:fix_rate] %></td>
      <td><%= stats[:avg_fix_time] %></td>
    </tr>
  <% end %>

</table>

app/scf_app/app/views/issues/stats_by_request_type_and_neighborhood.html.erb
<p>Results!</p>
<h2><%= @request_type %></h2>
<table>
  <tr>
    <td>neighborhood</td>
    <td>number of issues</td>
    <td>acknowledge rate</td>
    <td>fix rate</td>
    <td>average fix time (days)</td>
  </tr>
  <% @stats.each do |stats|%>
    <tr>
      <td><%= stats[:neighborhood] %></td>
      <td><%= stats[:n_issues] %></td>
      <td><%= stats[:acknowledge_rate] %></td>
      <td><%= stats[:fix_rate] %></td>
      <td><%= stats[:avg_fix_time] %></td>
    </tr>
  <% end %>

</table>

app/scf_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScfApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Get Stats</h1>
  <%= form_tag "/issues/stats_by_request_type" do%>
  last week<input type="radio" name="days_back", value='7'></input>
  last month<input type="radio" name="days_back", value='30'></input>
  last year<input type="radio" name="days_back", value='365'></input>
  all<input type="radio" name="days_back", value='0'></input>
    <%= submit_tag "by request type" %>
  <% end %>
  <%= form_tag "/issues/stats_by_neighborhood" do |f|%>
    last week<input type="radio" name="days_back", value='7'></input>
    last month<input type="radio" name="days_back", value='30'></input>
    last year<input type="radio" name="days_back", value='365'></input>
    all<input type="radio" name="days_back", value='0'></input>
    <%= submit_tag "by neighborhood" %>
  <% end %>
  <%= form_tag "/issues/stats_by_request_type_and_neighborhood" do |f|%>
    last week<input type="radio" name="days_back", value='7'></input>
    last month<input type="radio" name="days_back", value='30'></input>
    last year<input type="radio" name="days_back", value='365'></input>
    all<input type="radio" name="days_back", value='0'></input>
    <%= submit_tag "by request type then by neighborhood" %>
    <select name="request_type">
      <option value="Bins for Trash & Recycling">Bins for Trash and Recycling</option>
      <option value="Graffiti">Graffiti</option>
      <option value="Hangers">Hangers</option>
      <option value="Health Complaints">Health Complaints</option>
      <option value="Illegal Dumping">Illegal Dumping</option>
      <option value="Other">Other</option>
      <option value="Other - city responsibility">Other - city responsibility</option>
      <option value="Parking Violation/Abandoned Auto">Parking Violation/Abandoned Auto</option>
      <option value="Parks Request">Parks Request</option>
      <option value="Policing Issue">Policing Issue</option>
      <option value="Potholes">Potholes</option>
      <option value="Private Property Issue">Private Property Issue</option>
      <option value="Public Space, Streets and Drains">Public Space, Streets and Drains</option>
      <option value="Sidewalks and Curb damage">Sidewalks and Curb damage</option>
      <option value="Signs / Bus Shelters / Pavement Markings">Signs / Bus Shelters / Pavement Markings</option>
      <option value="Street Lamp">Street Lamp</option>
      <option value="Street Sweeping">Street Sweeping</option>
      <option value="Traffic/Road Safety">Traffic/Road Safety</option>
      <option value="Traffic Signal / Pedestrian Signal">Traffic Signal / Pedestrian Signal</option>
      <option value="Trash & Recycling">Trash and Recycling</option>
      <option value="Tree Trimming">Tree Trimming</option>
    </select>
  <% end %>

<%= yield %>

</body>
</html>

app/scf_app/app/views/layouts/clusters_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScfApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/scf_app/app/views/layouts/clusters_show_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScfApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm58egAUOadPo5D7aGStqWvybk6A68JQE&callback=initMap"
    async defer></script>
</head>
<body>

<%= yield %>

</body>
</html>