app/sandbox/config/routes.rb
Rails.application.routes.draw do
  resources :issues

end

app/sandbox/app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/sandbox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/sandbox/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.where(rtt: "Tree Trimming").group('street_name').sum(1)

  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issues = Issue.where(:street_name => 'Chapel Street')
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:status, :created_at, :neighborhood, :street_name, :acknowledged, :rtid, :rtt, :adress, :lat, :lng, :id_, :integer)
    end
end

app/sandbox/app/helpers/application_helper.rb
module ApplicationHelper
end

app/sandbox/app/helpers/issues_helper.rb
module IssuesHelper
end

app/sandbox/app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.text_field :neighborhood %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br>
    <%= f.text_field :street_name %>
  </div>
  <div class="field">
    <%= f.label :acknowledged %><br>
    <%= f.check_box :acknowledged %>
  </div>
  <div class="field">
    <%= f.label :rtid %><br>
    <%= f.text_field :rtid %>
  </div>
  <div class="field">
    <%= f.label :rtt %><br>
    <%= f.text_field :rtt %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :id_ %><br>
    <%= f.text_field :id_ %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/sandbox/app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/sandbox/app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Created at</th>
      <th>Neighborhood</th>
      <th>Street name</th>
      <th>Acknowledged</th>
      <th>Rtid</th>
      <th>Rtt</th>
      <th>Adress</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Id </th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |street_name,count| %>
      <tr>
        <td><%= street_name %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/sandbox/app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/sandbox/app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @issue.created_at %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @issue.neighborhood %>
</p>

<p>
  <strong>Street name:</strong>
  <%= @issue.street_name %>
</p>

<p>
  <strong>Acknowledged:</strong>
  <%= @issue.acknowledged %>
</p>

<p>
  <strong>Rtid:</strong>
  <%= @issue.rtid %>
</p>

<p>
  <strong>Rtt:</strong>
  <%= @issue.rtt %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @issue.adress %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @issue.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @issue.lng %>
</p>

<p>
  <strong>Id :</strong>
  <%= @issue.id_ %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @issue.integer %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/sandbox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>